MIN_RATIO_REGION = 0.5
MAX_RATIO_REGION = 0.99
PADDING_REGION = -7
REPL_PAD_REGION = False

MIN_RATIO_SECTION = 0.1
MAX_RATIO_SECTION = 0.9
PADDING_SECTION = -9
REPL_PAD_SECTION = False
TOLERANCE_SECTION = 10

MIN_RATIO_FIELD = 0.01
MAX_RATIO_FIELD = 0.1
PADDING_FIELD = -9
REPL_PAD_FIELD = False
TOLERANCE_FIELD = 10

MIN_RATIO_CHARACTER = 0.0
MAX_RATIO_CHARACTER = 0.9
PADDING_CHARACTER = 0
REPL_PAD_CHARACTER = False
TOLERANCE_CHARACTER = 100

FORM_LABEL = ['S','S','S','F','D','N']
FORM_SHAPE = [1,1,1,2,3,1]
FIELD_JOIN = ['','','','.','-','']

SHOW_DETECTED_CONTOURS = False
SHOW_PREPROCESSING = False
SHOW_REGION = True
SHOW_SECTION = False
SHOW_FIELD = False
SHOW_CHARACTER = False